#Server Specifics
server:
  port: 8083

spring:  
  application:
    name: flight-reservation
  h2:
    console:
        enabled: false
        path: /h2-console
        settings:
            trace: false
            web-allow-others: false
  datasource:
      driverClassName: org.h2.Driver
      password: ''
      url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/